name: Use Setup-Miniconda From Marketplace
on: [push]

jobs:
  job_1: # https://game.ci/docs/github/builder
    name: BuildUnity
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-StandaloneLinux64
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneLinux64
          projectPath: .
          buildName: StandaloneLinux64
          buildsPath: build

      - uses: actions/upload-artifact@v2
        with:
          name: Build-Linux
          path: build/StandaloneLinux64
